(ns euler-clj-2021.problems.p2
  (:require [euler-clj-2021.math.numbers :refer [fibonacci]]))

;; Each new term in the Fibonacci sequence is generated by adding the previous 
;; two terms. By starting with 1 and 2, the first 10 terms will be:

;; 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

;; By considering the terms in the Fibonacci sequence whose values do not exceed 
;; four million, find the sum of the even-valued terms.

(->> (fibonacci 1 2)
     (take-while #(<= % 4000000))
     (filter #(= 0 (mod % 2)))
     (reduce +))